activity/urls.py
from django.urls import path
from .views import (ActivityListView, ActivityDeleteView, 
    ActivityDetailView, ActivityUpdateView, ActivityPostListView)
from . import views

"""this file maps all our urls and displays them 
   path contains the arguments(url link, httpResponse(function in views.py), alias for url)
"""

app_name = "activity"
urlpatterns = [
    path('user/<str:username>/activity/', ActivityListView.as_view(), name='activity-list'),
    path('activity/new/', views.CreateActivity, name='activity-create'),
    path('activity/<int:pk>/', ActivityDetailView.as_view(), name='activity-detail'),
    path('<str:username>/<int:pk>/<slug:slug>/', ActivityPostListView.as_view(), name='activitypost-detail'),
    path('bookmark_activity/<int:pk>', views.bookmark_activity, name='bookmark-activity'),
    path('activity/bookmarks/', views.bookmarks, name='bookmark-list'),
    path('activity/<int:pk>/<slug:slug>/update/', ActivityUpdateView.as_view(), name='activity-update'), 
    path('activity/<int:pk>/<slug:slug>/delete/', ActivityDeleteView.as_view(), name='activity-delete')
]

blog/urls.py
from django.urls import path
from .views import (PostDetail, 
	PostUpdateView, PostDeleteView,
	IndexView)

from . import views

"""this file maps all our urls and displays them 
   path contains the arguments(url link, httpResponse(function in views.py), alias for url)
"""
app_name = "post"

urlpatterns = [
	path('', IndexView.as_view(), name='index-home'),
    path('home', views.home, name='blog-home'), 
    # path('post/new/', PostCreateView.as_view(), name='post-create'),
    path('user/<str:username>/', views.UserPosts, name='user-posts'),
    # path('user/<str:username>/', PostListActivityView.as_view(), name='user-posts'), 
    path('post/<str:username>/<int:pk>/', views.PostDetail, name='post-detail'),
    path('create-post/', views.createPost, name='create-post'),
    path('post/<int:pk>/update/', PostUpdateView.as_view(), name='post-update'), 
    path('post/<int:pk>/delete/', PostDeleteView.as_view(), name='post-delete'),
    path('favorite/',views.favorite_post, name='favorite-post'), 
    path('<str:username>/favorites/', views.user_favorites, name='favorites_list'),
    path('like/',views.like_post, name='like-post'), 
    path('about', views.about, name='blog-about'),
    path('userssearch/', views.userSearch, name='search-users')
]

comments/urls.py
from django.urls import path
from .views import CommentDeleteView, CommentUpdateView, ReplyUpdateView 
from .import views 

app_name = "comment"

urlpatterns = [
	path('comment/<str:username>/<int:pk>/', views.PostComment, name='post-comment'),
	path('reply/comment/<int:pk>/', views.ReplyComment, name='reply-thread'),
	path('comment/<int:pk>/update', CommentUpdateView.as_view(), name='comment-update'),
	path('comment/<int:pk>/delete', CommentDeleteView.as_view(), name='comment-delete'),
	path('reply/<int:pk>/update', ReplyUpdateView.as_view(), name='reply-update'),
	path('like/comment/<int:pk>/',views.like_comment, name='like-comment')
]

projectActivity/urls.py
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from users import views as user_views #import the user views directly here rather than use include
from users.views import LoginView, registerProfile



urlpatterns = [
    path('admin/', admin.site.urls),
    path('register/', user_views.register, name="register"),
    path('create/profile', registerProfile, name='signup_profile'),
    path('profile/edit/', user_views.profile, name="edit-profile"),
    # this is a class-based view (as_view is a function that directs where the url should look for the template)
    path('login/', LoginView.as_view(), name="login"),
    path('logout/', auth_views.LogoutView.as_view(template_name='users/logout.html'), name="logout"),
    path('password-reset/', 
        auth_views.PasswordResetView.as_view(
            template_name='users/password_reset.html'), name="password_reset"
        ),
    path('password-reset/done/', 
        auth_views.PasswordResetDoneView.as_view(
            template_name='users/password_reset_done.html'), name="password_reset_done"
        ),
    path('password-reset-confirm/<uidb64>/<token>/', 
        auth_views.PasswordResetConfirmView.as_view(
            template_name='users/password_reset_confirm.html'), name="password_reset_confirm"
        ),
    path('password-reset-complete/', 
        auth_views.PasswordResetCompleteView.as_view(
            template_name='users/password_reset_complete.html'), name="password_reset_complete"
        ),
    path('', include('blog.urls')), #the include function processes the url and sends to the blogs url file for processing.
    path('', include('activity.urls')),
    path('', include('comments.urls')),
    path('', include('relationships.urls')),
    path('api/', include('activity.api.urls')),
    path('notifications/', include('notify.urls', namespace='notifications')),
    path('api-auth/', include('rest_framework.urls')),

]
#leaving the url string empty makes it the default home page i.e localhost:8000

#Deloying static files during development
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

urls.py
try:
    from django.conf.urls import url
except ImportError:
    from django.urls import url

from notify import views as nf

app_name = 'notifications'


urlpatterns = [
    url(r'^all/$', nf.notifications, name="all"),
    url(r'^api/update/$', nf.notification_update, name="update"),
    url(r'^mark/$', nf.mark, name='mark'),
    url(r'^mark-all/$', nf.mark_all, name='mark_all'),
    url(r'^delete/$', nf.delete, name='delete'),
    url(r'^rdr/(?P<notification_id>[\d]+)/$', nf.read_and_redirect,
        name='read_and_redirect'),
]

comments/models.py
from django.db import models
from django.utils import timezone
from blog.models import Post
from django.contrib.auth.models import User
from django.urls import reverse
# Create your models here.

class Comment(models.Model):
	author 		= models.ForeignKey(User, on_delete=models.CASCADE)
	post 		= models.ForeignKey(Post, on_delete=models.CASCADE)
	content 	= models.TextField()
	# slug 		= models.SlugField(max_length=50, unique=True, null=True)
	image		= models.ImageField(null=True, upload_to='post_pics', blank=True)
	likes		= models.ManyToManyField(User, related_name='comment_likes', blank=True)
	date_posted = models.DateTimeField(default=timezone.now)
	parent 		= models.ForeignKey('self', on_delete=models.CASCADE, null=True, blank=True, related_name='replies')


	def __str__(self):
		return self.content[:80]

	def get_absolute_url(self):
		return reverse('post:user-posts', kwargs={'username': self.author})

comments/forms.py
from django import forms
from .models import Comment

class CommentForm(forms.ModelForm):
	content = forms.CharField(label='', widget=forms.Textarea(attrs={'rows':3, 'placeholder':'Leave a comment...'}))
	image = forms.ImageField(label='', required=False)
	
	class Meta:
		model = Comment # User model to be affected 
		fields = ['content', 'image']

class ReplyForm(forms.ModelForm):
	content = forms.CharField(label='', widget=forms.Textarea(attrs={'rows':3, 'placeholder':'Leave a reply...'}))
	image = forms.ImageField(label='', required=False)
	
	class Meta:
		model = Comment # User model to be affected 
		fields = ['content', 'image']

comments/views.py
from django.shortcuts import render
from django.shortcuts import render, redirect, get_object_or_404
from django.views.generic import UpdateView, DeleteView
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.contrib.auth.models import User
from django.http import HttpResponseRedirect
from django.urls import reverse
from .models import Comment
from blog.models import Post
from .forms import CommentForm, ReplyForm
from notify.signals import notify

# Create your views here.

def PostComment(request, pk, username):
	post = get_object_or_404(Post, pk=pk)

	if request.method == 'POST':
		form = CommentForm(request.POST, request.FILES or None)
		if form.is_valid():
			comment = form.save(commit=False)
			comment.author = request.user
			comment.post = post
			comment.save()
			return redirect('post:post-detail', username, pk)
	else:
		form = CommentForm()

	context = {
		'object': post,
		'form': form
	}

	return render(request, 'comments/post_comment.html', context)

class CommentDeleteView(LoginRequiredMixin, UserPassesTestMixin, DeleteView):
	model = Comment

	def test_func(self):
		comment = self.get_object()
		if self.request.user == comment.author:
			return True
		return False

	def get_success_url(self):
		post = self.object.post.id
		username = self.object.author
		return reverse('post:post-detail', kwargs={'username': username ,'pk': post})

class CommentUpdateView(LoginRequiredMixin, UserPassesTestMixin, UpdateView):
	model = Comment
	form_class = CommentForm
	template_name = 'comments/edit_comment.html'

	def form_valid(self, form):
		form.instance.author = self.request.user
		form.instance.post_id = self.object.post.id
		form.instance.content = form.cleaned_data['content']
		return super().form_valid(form)

	def test_func(self):
		comment = self.get_object()
		if self.request.user == comment.author:
			return True
		return False
		
	def get_success_url(self):
		post = self.object.post.id
		username = self.object.author
		return reverse('post:post-detail', kwargs={'username':username, 'pk': post})

class ReplyUpdateView(LoginRequiredMixin, UserPassesTestMixin, UpdateView):
	model = Comment
	form_class = CommentForm
	template_name = 'comments/reply_form.html'

	def test_func(self):
		comment = self.get_object()
		if self.request.user == comment.author:
			return True
		return False
		
	def get_success_url(self):
		post = self.object.post.id
		username = self.object.author
		return reverse('post:post-detail', kwargs={'username':username, 'pk': post})

def ReplyComment(request, pk):
	comment = get_object_or_404(Comment, pk=pk)
	form = ReplyForm(request.POST or None)
	if request.method == 'POST':
		reply_form = ReplyForm(request.POST, request.FILES or None)
		if reply_form.is_valid():
			Parent_obj = None
			try:
				Parent_id = int(request.POST.get('parent_id')) #get the id of the form 
			except:
				Parent_id = None
			if Parent_id: 
				Parent_obj = Comment.objects.get(id=Parent_id) #get the parent obj from the comment model passing in the id value
				if Parent_obj:
					reply_comment = reply_form.save(commit=False) #saves the comment as a reply to another comment on the main post not as a comment on the main post
					reply_comment.author = request.user #saves the author object as the logged in user
					reply_comment.parent = Parent_obj # saves the comment as a reply
					reply_comment.post_id = Parent_obj.post.id
					reply_comment.content = reply_form.cleaned_data.get('content')
					notify.send(request.user, recipient=comment.author, actor=request.user, 
							verb='replied your comment', target=reply_comment.parent, nf_type='reply_by_user')
					reply_comment.save()

					parts = reply_comment.content.split()
					for index, value in enumerate(parts):
						if value.startswith("@"):
							results = value[1:]
							try:
								user = User.objects.get(username=results)
								notify.send(request.user, recipient=user, actor=request.user, 
										verb='mentioned you in a reply', target=reply_comment, nf_type='mentioned_comment_by_user')
							except user.DoesNotExist: 
								return redirect('comment:reply-thread', Parent_obj.id)
					return redirect('comment:reply-thread', Parent_obj.id)
			# # comment = reply_form.save(commit=False) # if no parent id is gotten save the comment as a new comment to the main post 
			# # comment.author = request.user # save username of the logged in user
			# comment.post = Parent_obj.post.id # saves the pk of the current post 
			# # comment.save()
			# return redirect('comment:reply-thread', pk)
	else:
		reply_form = ReplyForm() #if no value is gotten return the form
	context = {
		'comment': comment,
		'form': form
	}

	return render(request, 'comments/reply_comment.html', context)

def like_comment(request, pk):
	comment = get_object_or_404(Comment, pk=pk)

	if comment.likes.filter(id=request.user.id).exists():
		 comment.likes.remove(request.user)
	else:
		comment.likes.add(request.user)
		notify.send(request.user, recipient=comment.author, actor=request.user, 
				verb='liked your comment', target=comment, nf_type='like_by_user')
	return HttpResponseRedirect(comment.get_absolute_url())

comments/templates/comments/comment_confirm_delete.html
{% extends "blog/base.html"%}
{% block content %}
	<div class="content-section">
		<form method="POST">
			{% csrf_token %}
			<fieldset class="form-group">
				<legend clas="border-bottom mb-4">Are you sure you want to delete this comment?</legend>
				<!-- <h2>Are you sure you want to delete this comment"</h2> -->
				<p>{{object.content}}</p>
				{% if object.image %}
					<img src="{{object.image.url}}" class=" rounded img-fluid mb-4" alt="...">
				{% endif %}
			</fieldset>
			<div class="form-group">
				<button class="btn btn-outline-danger" type="submit">Yes, Delete</button>
				<a class="btn btn-outline-secondary"  href="{% url 'post:post-detail' object.author object.post.pk %}" type="submit">Cancel</a>
			</div>
		</form>
	</div>
{% endblock content %}

comments/templates/comments/comment_form.html
{% extends "blog/base.html"%}
{% load crispy_forms_tags %}
{% block content %}
	<div class="content-section">
		<form method="POST" enctype="multipart/form-data">
			{% csrf_token %}
			<fieldset class="form-group">
				<legend clas="border-bottom mb-4">Edit Comment</legend>
				{{ form|crispy }}
			</fieldset>
			<div class="form-group">
				<button class="btn btn-outline-info" type="submit">Update</button>
			</div>
		</form>
	</div>
{% endblock content %}

comments/templates/comments/edit_comment.html
{% extends "blog/base.html"%}
{% load crispy_forms_tags %}
{% block content %}
	<div class="media content-section">
		<img class="rounded-circle article-img" src="{{ object.author.profile.image.url }}">
		<div class="media-body">
			<div class="article-metadata">
				<a href="{% url 'post:user-posts' object.author.username %}"> {{ object.author }}</a>
				<small class="text-muted ml-2">{{ object.date_posted}} </small>
			</div>
			<form method="POST" enctype="multipart/form-data">
				{% csrf_token %}
				<fieldset class="form-group mt-2">
					{{ form.content|as_crispy_field}}
					<button class="btn btn-outline-info" type="submit">Update</button>
				</fieldset>
			</form>
		</div>
	</div>
{% endblock content %}

comments/templates/comments/post_comment.html
{% extends "blog/base.html"%}
{% load crispy_forms_tags %}

{% block content %}
	<article class="media content-section">
		<img class="rounded-circle article-img" src="{{ object.author.profile.image.url }}">
		<div class="media-body">
			<div class="article-metadata">
				<!-- here we used the default naming convention of class based view(object). Check the postlistview for how its changed -->
				<a class="mr-2" href="{% url 'post:user-posts' object.author.username %}">{{ object.author}}</a>
				<small class="text-muted">{{ object.date_posted|date:"F d, Y" }}</small>
			</div>
			<small class="text-muted">Posted in<a href="{% url 'activity:activitypost-detail' object.author object.activity.id object.activity.slug %}"> {{ object.activity }}</a> </small>
			<h2 class="article-title">{{ object.title}}</h2>
			<p class="article-content">{{ object.content }}</p>
			{% if object.image %}
				<img src="{{object.image.url}}" class=" rounded img-fluid mb-4" alt="...">
			{% endif %}
		</div>
	</article>
		<div class="media mb-4">
		  <img src="{{ user.profile.image.url }}" class="rounded-circle article-img mr-3" alt="...">
		  <div class="media-body">
			    <form method="POST" enctype="multipart/form-data">
					{% csrf_token %}
					<fieldset class="form-group">
						{{ form|crispy }}
					</fieldset>
					<div class="form-group">
						<button class="btn btn-outline-info" type="submit">Post</button>
					</div>
				</form>
		  </div>
		</div>
{% endblock%}

comments/templates/comments/reply_comment.html
{% extends "blog/base.html"%}
{% load crispy_forms_tags %}
{% load filters %}

{% block content %}
<h6><a href="{% url 'post:post-detail' comment.author comment.post.id%}"> < Back to Post</a></h6>
    <div class="media mt-3">
     <img class="rounded-circle article-img" src="{{ comment.author.profile.image.url }}">
      	<div class="media-body">
	      	<div class="article-meta-data">
				<a class="mr-2" href="{% url 'post:user-posts' comment.author.username %}">{{ comment.author}}</a>
				<small class="text-muted">{{ comment.date_posted|timesince }}</small>
				{% if user == comment.author %}
					<div class="edit-elipsis" id="navbarNavDropdown">
					    <ul class="navbar-nav">
						    <li class="nav-item dropdown">
						       <a class="nav-link dropdown-toggle" href="#" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"></a>
						        <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
						          <a class="dropdown-item" href="{% url 'comment:comment-update' comment.id %}">Edit</a>
						          <a class="dropdown-item" href="{% url 'comment:comment-delete' comment.id %}">Delete</a>
						        </div>
						    </li>
					    </ul>
				 	</div>
				{% endif %}
			</div>
			<p class="article-content">{{ comment.content }}</p>
			{% if comment.image %}
				<img src="{{comment.image.url}}" class=" rounded img-fluid mb-4" alt="...">
			{% endif %}
			<footer><small><a href="">Like</a></small>
			<p class="comment-hr"><span>Replies</span></p>
		</div>
		</div>
		{% for reply in comment.replies.all %}
			<div class="media">
				<img class="rounded-circle article-img" src="{{ reply.author.profile.image.url }}">
					<div class="media-body">
						<div class="article-meta-data">
							<a class="mr-2" href="{% url 'post:user-posts' reply.author.username %}">{{ reply.author}}</a>
							<small class="text-muted">{{ reply.date_posted }}</small>
							{% if user == reply.author %}
								<div class="edit-elipsis" id="navbarNavDropdown">
								    <ul class="navbar-nav">
									    <li class="nav-item dropdown">
									       <a class="nav-link dropdown-toggle" href="#" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"></a>
									        <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
									          <a class="dropdown-item" href="{% url 'comment:reply-update' reply.id %}">Edit</a>
									          <a class="dropdown-item" href="{% url 'comment:comment-delete' reply.id %}">Delete</a>
									        </div>
									    </li>
								    </ul>
							 	</div>
							{% endif %}
						</div>
						{% autoescape off %}
							<p class="article-content">{{ reply.content | parse_content}}</p>
						{% endautoescape %}
						{% if reply.image %}
							<img src="{{reply.image.url}}" class=" rounded img-fluid mb-4" alt="...">
						{% endif %}
						<footer><small><a href="">Like</a></small>
							<hr class="mt-2">
					</div>
			</div>
		{% endfor %}

		<div class="media mt-2">
			<img class="rounded-circle article-img" src="{{ user.profile.image.url }}">
			<div class="media-body">
			    <form method="POST" enctype="multipart/form-data">
					{% csrf_token %}
					<fieldset class="form-group">
						<input type="hidden" name="parent_id" value="{{ comment.id }}">
						{{ form|crispy }}
					</fieldset>
					<div class="form-group">
						<button class="btn btn-outline-info" type="submit">Reply</button>
					</div>
				</form>
			</div>
		</div>

{% endblock%}

comments/templates/comments/reply_form.html
{% extends "blog/base.html"%}
{% load crispy_forms_tags %}
{% block content %}
	<div class="content-section">
		<form method="POST" enctype="multipart/form-data">
			{% csrf_token %}
			<fieldset class="form-group">
				<legend clas="border-bottom mb-4">Edit Reply</legend>
				{{ form|crispy }}
			</fieldset>
			<div class="form-group">
				<button class="btn btn-outline-info" type="submit">Update</button>
			</div>
		</form>
	</div>
{% endblock content %}