activity/api/urls.py
from django.urls import path

from activity.api.apiviews import UserActivityList, CreateActivity, ActivityList

urlpatterns = [
path('activitylist/<str:username>', UserActivityList.as_view(), name='user_activity_list'),
path('activity/<int:pk>', ActivityList.as_view(), name='activity'),
path('create/', CreateActivity.as_view(), name='create_activity'),
]

activity/urls.py
from django.urls import path
from .views import (ActivityListView, ActivityDeleteView, 
    ActivityDetailView, ActivityUpdateView, ActivityPostListView)
from . import views

"""this file maps all our urls and displays them 
   path contains the arguments(url link, httpResponse(function in views.py), alias for url)
"""

app_name = "activity"
urlpatterns = [
    path('user/<str:username>/activity/', ActivityListView.as_view(), name='activity-list'),
    path('activity/new/', views.CreateActivity, name='activity-create'),
    path('activity/<int:pk>/', ActivityDetailView.as_view(), name='activity-detail'),
    path('<str:username>/<int:pk>/<slug:slug>/', ActivityPostListView.as_view(), name='activitypost-detail'),
    path('bookmark_activity/<int:pk>', views.bookmark_activity, name='bookmark-activity'),
    path('activity/bookmarks/', views.bookmarks, name='bookmark-list'),
    path('activity/<int:pk>/<slug:slug>/update/', ActivityUpdateView.as_view(), name='activity-update'), 
    path('activity/<int:pk>/<slug:slug>/delete/', ActivityDeleteView.as_view(), name='activity-delete')
]

blog/urls.py
from django.urls import path
from .views import (PostDetail, 
	PostUpdateView, PostDeleteView,
	IndexView)

from . import views

"""this file maps all our urls and displays them 
   path contains the arguments(url link, httpResponse(function in views.py), alias for url)
"""
app_name = "post"

urlpatterns = [
	path('', IndexView.as_view(), name='index-home'),
    path('home', views.home, name='blog-home'), 
    # path('post/new/', PostCreateView.as_view(), name='post-create'),
    path('user/<str:username>/', views.UserPosts, name='user-posts'),
    # path('user/<str:username>/', PostListActivityView.as_view(), name='user-posts'), 
    path('post/<str:username>/<int:pk>/', views.PostDetail, name='post-detail'),
    path('create-post/', views.createPost, name='create-post'),
    path('post/<int:pk>/update/', PostUpdateView.as_view(), name='post-update'), 
    path('post/<int:pk>/delete/', PostDeleteView.as_view(), name='post-delete'),
    path('favorite/',views.favorite_post, name='favorite-post'), 
    path('<str:username>/favorites/', views.user_favorites, name='favorites_list'),
    path('like/',views.like_post, name='like-post'), 
    path('about', views.about, name='blog-about'),
    path('userssearch/', views.userSearch, name='search-users')
]

projectActivity/urls.py
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from users import views as user_views #import the user views directly here rather than use include
from users.views import LoginView, registerProfile



urlpatterns = [
    path('admin/', admin.site.urls),
    path('register/', user_views.register, name="register"),
    path('create/profile', registerProfile, name='signup_profile'),
    path('profile/edit/', user_views.profile, name="edit-profile"),
    # this is a class-based view (as_view is a function that directs where the url should look for the template)
    path('login/', LoginView.as_view(), name="login"),
    path('logout/', auth_views.LogoutView.as_view(template_name='users/logout.html'), name="logout"),
    path('password-reset/', 
        auth_views.PasswordResetView.as_view(
            template_name='users/password_reset.html'), name="password_reset"
        ),
    path('password-reset/done/', 
        auth_views.PasswordResetDoneView.as_view(
            template_name='users/password_reset_done.html'), name="password_reset_done"
        ),
    path('password-reset-confirm/<uidb64>/<token>/', 
        auth_views.PasswordResetConfirmView.as_view(
            template_name='users/password_reset_confirm.html'), name="password_reset_confirm"
        ),
    path('password-reset-complete/', 
        auth_views.PasswordResetCompleteView.as_view(
            template_name='users/password_reset_complete.html'), name="password_reset_complete"
        ),
    path('', include('blog.urls')), #the include function processes the url and sends to the blogs url file for processing.
    path('', include('activity.urls')),
    path('', include('comments.urls')),
    path('', include('relationships.urls')),
    path('api/', include('activity.api.urls')),
    path('notifications/', include('notify.urls', namespace='notifications')),
    path('api-auth/', include('rest_framework.urls')),

]
#leaving the url string empty makes it the default home page i.e localhost:8000

#Deloying static files during development
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

urls.py
try:
    from django.conf.urls import url
except ImportError:
    from django.urls import url

from notify import views as nf

app_name = 'notifications'


urlpatterns = [
    url(r'^all/$', nf.notifications, name="all"),
    url(r'^api/update/$', nf.notification_update, name="update"),
    url(r'^mark/$', nf.mark, name='mark'),
    url(r'^mark-all/$', nf.mark_all, name='mark_all'),
    url(r'^delete/$', nf.delete, name='delete'),
    url(r'^rdr/(?P<notification_id>[\d]+)/$', nf.read_and_redirect,
        name='read_and_redirect'),
]

activity/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User
from django.urls import reverse
# from django_extensions.db.fields import AutoSlugField 
# Create your models here.

class Activity(models.Model):
	author 			= models.ForeignKey(User, on_delete=models.CASCADE)
	name 			= models.CharField(max_length=250)
	slug 			= models.SlugField(null=True, max_length=50)
	# slug = AutoSlugField(_('slug'), max_length=50, unique=True, populate_from=('name'), null=True)
	description 	= models.TextField()
	# target 			= models.TextField(max_length=150)
	image			= models.ImageField(null=True, upload_to='activity_pics', blank=True)
	category_chocies = (('Arts', 'Arts'), ('Adventure', 'Adventure'), 
		('Business', 'Business'), ('Design', 'Design'), ('Entertainment', 'Entertainment'), ('Education', 'Education'), 
		('Health', 'Health'), ('Fitness', 'Fitness'), 
		('Fashion', 'Fashion'), ('Food', 'Food'), ('Music', 'Music'), ('Programming', 'Programming'), ('Startup', 'Startup'),
		('Technology', 'Technology'), ('Other', 'Other'), )
	category		= models.CharField(max_length=100, default=None, choices=category_chocies, null=True)
	bookmark		= models.ManyToManyField(User, related_name='bookmark', blank=True)
	start_date 		= models.DateTimeField(default=timezone.now)
	end_date		= models.DateTimeField(default=timezone.now)
	date_posted	 	= models.DateTimeField(default=timezone.now) #set to the actual time the post was updated

	def __str__(self):
		return self.name

	def get_absolute_url(self):
		return reverse('activity:activity-list', kwargs={'username': self.author })

	# def save(self, *args, **kwargs):
	# 	super(Activity, self).save(*args, **kwargs) #run the save method of parent class(profile)

	# 	img = Image.open(self.image.path)

	# 	if img.height > 300 and img.width > 300: #checks the height and width of the image 
	# 		output_size = (300, 300)
	# 		img.thumbnail(output_size)
	# 		img.save(self.image.path)

activity/forms.py
from django import forms
from .models import Activity
from .widgets import FengyuanChenDatePickerInput
import datetime

class ActivityForm(forms.ModelForm):
	name		= forms.CharField(widget=forms.TextInput(attrs={'placeholder': 'Give a name to the activity you want to start'}))
	description = forms.CharField(label='Description', widget=forms.Textarea(attrs={'rows':4, 'placeholder':'Give a brief description of the activity you want to start'}))
	# target		= forms.CharField(label='Target', widget=forms.Textarea(attrs={'placeholder':'What do you aim to achieve at the end of your activity'}))
	start_date	= forms.DateField(input_formats=['%d/%m/%Y'], widget=forms.DateInput(attrs={'placeholder':'Select a start date'}))
	end_date	= forms.DateField(input_formats=['%d/%m/%Y'], widget=forms.DateInput(attrs={'placeholder':'Select an end date'}))
	image = forms.ImageField(label='', required=False)
	CATEGORY_SELECT = (('', 'Choose a category'), ('Arts', 'Arts'), ('Adventure', 'Adventure'), 
		('Business', 'Business'), ('Design', 'Design'), ('Entertainment', 'Entertainment'), ('Education', 'Education'), 
		('Health', 'Health'), ('Fitness', 'Fitness'), 
		('Fashion', 'Fashion'), ('Food', 'Food'), ('Music', 'Music'), ('Programming', 'Programming'), ('Startup', 'Startup'),
		('Technology', 'Technology'), ('Other', 'Other'), )
	category = forms.ChoiceField(label='', choices=CATEGORY_SELECT, widget=forms.Select(attrs={'empty_label': 'Choose a category'}))

	class Meta:
		model = Activity
		fields = ['name','description', 'category', 'image','start_date','end_date']

	def clean_start_date(self):
		start_date = self.cleaned_data['start_date']
		if start_date < datetime.date.today():
			raise forms.ValidationError("Start date cannot be in the past")
		return start_date

	def clean_end_date(self):
		end_date = self.cleaned_data['end_date']
		if end_date < datetime.date.today():
			raise forms.ValidationError("End date cannot be in the past")
		return end_date

activity/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.http import HttpResponseRedirect
from django.contrib.auth.models import User
from django.views.generic import ListView, DetailView, CreateView, UpdateView, DeleteView, FormView
from django.views import View
from .models import Activity
from .forms import ActivityForm
from blog.models import Post
from relationships.models import Relationship
from blog.forms import PostForm
from django.urls import reverse

# Create your views here.

# class ActivityCreateView(CreateView):
# 	model = Activity # model to be affected
# 	# fields = ['name', 'description', 'category', 'target'] # fields to be updated
# 	form_class = ActivityForm
# 	template_name = 'activity/activity_create.html'

# 	def form_valid(self, form):
# 		form.instance.author = self.request.user
# 		return super().form_valid(form)

def CreateActivity(request):
	if request.method == 'POST':
		form = ActivityForm(request.POST)
		if form.is_valid():
			form.instance.author = request.user
			new_form = form.save()
			username = form.cleaned_data.get('author')
			return redirect('activity:activity-list', request.user)
	else:
		form = ActivityForm()

	context= {
		'form': form
	}

	return render(request, 'activity/activity_create.html', context)



class ActivityListView(ListView):
	model = Activity # model to be affected
	template_name = 'activity/activity_list.html' #<app>/<model>_<viewtype>.html
	context_object_name = 'activities' #by default it expects the context to be called object here it is changed to posts as above.
	ordering = ['-date_posted'] #this orders the post in ascending order (most recent post to older post)
	paginate_by = 5 #reduces the amount of posts displayed per page

	def get_queryset(self):
		user = get_object_or_404(User, username=self.kwargs.get('username')) 
		return Activity.objects.filter(author=user).order_by('-date_posted') # the activity model object is filtered to return only posts from a certain  user
	
	""" the get_context_data function of the listview class is overriden to return an instance of the user object """
	def get_context_data(self, **kwargs):
		context = super(ActivityListView, self).get_context_data(**kwargs) 
		user = get_object_or_404(User, username=self.kwargs.get('username'))
		posts = Post.objects.filter(author=user).count()
		activities = Activity.objects.filter(author=user).count()
		following  = Relationship.objects.filter(from_user=user).count()
		followers  = Relationship.objects.filter(to_user=user).count()
		context['posts_count'] = posts
		context['activities_count'] = activities
		context['following_count'] = following
		context['followers_count'] = followers  
		context['user_profile'] = user #saves the user object as user_profile
		return context

class ActivityPostListView(ListView):
	model = Activity # model to be affected
	context_object_name = 'activity'
	template_name = 'activity/activity_post_detail.html'
	# ordering = ['-date_posted']
	paginate_by = 10
	
	def get_queryset(self):
		user = get_object_or_404(User, username=self.kwargs.get('username'))
		post = get_object_or_404(Activity, pk=self.kwargs.get('pk'), slug=self.kwargs.get('slug')) 
		return Post.objects.filter(author=user, activity=post)

	def get_context_data(self, **kwargs):
		context = super().get_context_data(**kwargs) 
		user = get_object_or_404(User, username=self.kwargs.get('username'))
		activity = get_object_or_404(Activity, pk=self.kwargs.get('pk'))
		posts = Post.objects.filter(author=user).count()
		activities = Activity.objects.filter(author=user).count()
		following  = Relationship.objects.filter(from_user=user).count()
		followers  = Relationship.objects.filter(to_user=user).count()
		context['posts_count'] = posts
		context['activities_count'] = activities
		context['following_count'] = following
		context['followers_count'] = followers  
		context['user_profile'] = user #saves the user object as user_profile
		context['activities'] = activity
		context['is_liked'] = Post.objects.filter(likes__username=self.request.user.username).values_list('id', flat=True)
		context['is_favorite'] = Post.objects.filter(favorite__username=self.request.user.username).values_list('id', flat=True)
		is_bookmarked = False
		if activity.bookmark.filter(pk=user.id).exists():
			is_bookmarked = True
		context['is_bookmarked'] = is_bookmarked
		return context


class ActivityDetailView(DetailView):
	model = Activity # model to be affected

class ActivityUpdateView(LoginRequiredMixin, UserPassesTestMixin, UpdateView):
	model = Activity # model to be affected
	fields = ['name', 'description', 'target'] # fields to be updated
	template_name = 'activity/activity_create.html'

	def form_valid(self, form):
		form.instance.author = self.request.user
		return super().form_valid(form)

	def test_func(self):
		post = self.get_object() #get_object is a method of the UpdateView which gets the post object
		if self.request.user == post.author: # if the logged in user is the author of the post trying to be updated
			return True
		return False

class ActivityDeleteView(LoginRequiredMixin, UserPassesTestMixin, DeleteView):
	model = Activity # model to be affected

	def get_success_url(self):
		activity = self.object.author
		# activity_slug = self.object.slug
		return reverse('activity-list', kwargs={'username': activity})

	def test_func(self):
		activity = self.get_object() #get_object is a method of the UpdateView which gets the post object
		if self.request.user == activity.author: # if the logged in user is the author of the post trying to be updated
			return True
		return False

def bookmark_activity(request, pk):
	activity = get_object_or_404(Activity, pk=pk)

	if activity.bookmark.filter(id=request.user.id).exists():
		activity.bookmark.remove(request.user)
	else: 
		activity.bookmark.add(request.user)
	return HttpResponseRedirect(activity.get_absolute_url())

def bookmarks(request):
	user = request.user
	bookmark_activity = user.bookmark.all().order_by('-id') 

	context={
		'bookmark_activity': bookmark_activity,
		'user_profile': user
		}

	return render(request, 'activity/bookmarks.html', context)

activity/templates/activity/activity_confirm_delete.html
{% extends "blog/base.html"%}
{% block content %}
	<div class="content-section">
		<form method="POST">
			{% csrf_token %}
			<fieldset class="form-group">
				<legend clas="border-bottom mb-4"> Are you sure you want to delete this activity?</legend>
				<h4></h4>
				<h2>{{ object.name }}</h2>
				<p> {{ object.description }}</p>
				<p>{{ object.target }}</p>
			</fieldset>
			<div class="form-group">
				<button class="btn btn-outline-danger" type="submit">Yes, Delete</button>
				<a class="btn btn-outline-secondary"  href="{% url 'activity:activity-detail' object.id %}" type="submit">Cancel</a>
			</div>
		</form>
	</div>
{% endblock content %}

activity/templates/activity/activity_create.html
{% extends "blog/base.html"%}
{% load crispy_forms_tags %}
{% block content %}
	<div class="content-section">
		<form method="POST" autocomplete="off">
			{% csrf_token %}
			<fieldset class="form-group">
				<legend clas="border-bottom mb-4">Create a new Activity</legend>
				{{ form.name|as_crispy_field }}
				{{ form.description|as_crispy_field }}
				<div class="form-row">
					<div class="form-group col-md-4">
						{{ form.image|as_crispy_field }}
					</div>
					<div class="form-group col-md-8">
						{{ form.category|as_crispy_field }}
					</div>
				</div>
				<div class="form-row">
					<div class="form-group col-md-6">
						{{ form.start_date|as_crispy_field }}
					</div>
					<div class="form-group col-md-6">
					    {{ form.end_date|as_crispy_field }}
					</div>
				</div>
					<button class="btn btn-outline-info" type="submit">Create Activity</button>
			</fieldset>
		</form>
	</div>
{% endblock content %}

activity/templates/activity/activity_detail.html
<!-- imports the base file here -->
{% extends "blog/base.html"%}

<!-- displays the posts in the base.html file -->
{% block content %}
	<article class="media content-section">
		<img class="rounded-circle article-img" src="{{ object.author.profile.image.url }}">
		<div class="media-body">
			<div class="article-meta-data">
				<!-- here we used the default naming convention of class based view(object). Check the postlistview for how its changed -->
				<a class="mr-2" href="{% url 'post:user-posts' object.author.username %}">{{ object.author}}</a>
				<small class="text-muted">{{ object.date_posted|date:"F d, Y" }}</small>
			</div>
				<h2 class="article-title">{{ object.name }}</h2>
				<p class="article-content">{{ object.description }}</p>
				<p class="article-content">{{ object.target }}</p>
				<p class="article-content">Read all the posts in <a href="{% url 'activity:activitypost-detail' object.author.username object.pk object.slug %}">{{ object.name}}</a></p>
				{% if object.author == user %}
					<div>
						<a class="btn btn-secondary btn-small mt-1 mb-1" href="{% url 'activity:activity-update' object.id object.slug %}">Update</a>
						<a class="btn btn-danger btn-small mt-1 mb-1" href="{% url 'activity:activity-delete' object.id object.slug %}">Delete</a>
					</div>
				{% endif %}
		</div>
	</article>	
{% endblock content %}

activity/templates/activity/activity_list.html
<!-- imports the sidebar file here -->
{% extends "blog/sidebar.html" %}
<!-- displays the the block contents in this html in the block content of base.html file -->

{% block followbutton %} 
	{% include "relationship/follow_button.html" %}
{% endblock followbutton %}

{% block content %}
{% if user == user_profile and activities.count < 0 %}
	<div class="card">
	  <div class="card-body">
	  	<p>You don't have any activites yet. </p><a href="{% url 'activity:activity-create' %}">Create a new activity to start sharing your journey with your friends.</a>
	  </div>
	</div>

	{% elif user != user_profile and activities.count == 0 %}
	<article class="media content-section mt-3">
		<div class="media-body mb-4">
			{{user_profile.username}} hasn't started any activities yet...
		</div>
	</article>

	{% elif user == user_profile and activities.count > 0 %}
	<div class="card">
		<div class="card-body">
			<h6><a href="{% url 'activity:activity-create' %}">Start a new activity</a></h6>
		</div>
	</div>
{% endif %}

	{% for activity in activities %}
		<article class="media content-section mt-3">
			<img class="rounded-circle article-img" src="{{ activity.author.profile.image.url }}">
			<div class="media-body">
				<div class="article-metadata">
					<a href="{% url 'post:user-posts' activity.author.username %}"> {{ activity.author }}</a>
					<small class="text-muted ml-2">{{ activity.date_posted | timesince }} ago</small>
					<a class="ml-4" href="#">XXX</a>
					{% if user == activity.author %}
						<ul class="dropdown">
							<div class="dropdown edit-elipsis">
						       <a class="nav-link dropdown-toggle" href="#" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"></a> <span class="caret"></span>
						        <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
						          <a class="dropdown-item" href="{% url 'activity:activity-update' activity.id activity.slug %}">Edit</a>
						          <a class="dropdown-item" href="{% url 'activity:activity-delete' activity.id activity.slug %}">Delete</a>
						          <a class="dropdown-item" href="#">Something else here</a>
						        </div>
						 	</div>
						</ul>
					{% endif %}
			 	</div>
			 	<div class="article-metadata">
					<h4>{{ activity.name}}</h4>
					<p class="article-content">{{ activity.description }}</p>
				</div>
				<p><a href="{% url 'activity:activitypost-detail' activity.author activity.id activity.slug %}">View all posts in {{activity.name}}</a></p>
			</div>
		</article>
	{% endfor %}

	<!-- is_paginated is a variable available from the paginator object in the PostListView -->
	{% if is_paginated %}
		<!-- if codeblock to display the first and previous pages as a button -->
		{% if page_obj.has_previous %}
			<a class="btn btn-outline-info mb-4" href="?page=1">First</a>
			<a class="btn btn-outline-info mb-4" href="?page={{ page_obj.previous_page_number }}">Previous</a>
		{% endif %}

		{% for num in page_obj.paginator.page_range %}
			{% if page_obj.number == num %}
				<a class="btn btn-info mb-4" href="?page={{ num }}">{{ num }}</a>
			{% elif num > page_obj.number|add:'-3' and num < page_obj.number|add:'3' %}
				<a class="btn btn-outline-info mb-4" href="?page={{ num }}">{{ num }}</a>
			{% endif %}
		{% endfor %}

		{% if page_obj.has_next %}
			<a class="btn btn-outline-info mb-4" href="?page={{ page_obj.next_page_number}}">Next</a>
			<a class="btn btn-outline-info mb-4" href="?page={{ page_obj.paginator.num_pages }}">Last</a>
		{% endif %}
	{% endif %}
{% endblock content %}

activity/templates/activity/activity_post_detail.html
<!-- imports the base file here -->
{% extends "blog/sidebar.html" %}
<!-- displays the the block contents in this html in the block content of base.html file -->
{% load crispy_forms_tags %}

{% block followbutton %} 
	{% include "relationship/follow_button.html" %}
{% endblock followbutton %}

{% block content %}
<div class="card text-center mb-4 ">
	<div class="card-header">
  		<h4> {{activities.name}} 
  			{% if is_bookmarked %}
  				<a class="ml-4" href="{% url 'activity:bookmark-activity' pk=activities.id %}">XX</a> 
  			{% else %}
  				<a class="ml-4" href="{% url 'activity:bookmark-activity' pk=activities.id %}">yy</a>
  			{% endif %}
  		</h4>
  	</div>
  	<div class="card-body">
    	<p class="card-text"> {{ activities.description }} </p>
    	{% if user == user_profile %}
	  		<a href="{% url 'post:user-posts' activities.author %}" class="btn btn-primary">Share a post</a>
	{% endif %}
  	</div>
  	<div class="card-footer text-muted">
    	Start date({{ activities.start_date }}) to End date ({{ activities.end_date }})
  	</div>
</div>

{% if activity.count == 0 %}
	<div class="card mb-4">
		<div class="card-body">
	  		<h6>No posts have been shared to this activity yet.</h6>
	  	</div>
	</div>
{% endif %}

{% for post in activity %}
	<article class="media content-section">
		<img class="rounded-circle article-img" src="{{ post.author.profile.image.url }}">
		<div class="media-body">
			<div class="article-metadata">
				<a class="mr-2" href="{% url 'post:user-posts' post.author.username %}">{{ post.author}}</a>
				<small class="text-muted">{{ activities.end_date | timeuntil:post.date_posted}} ago</small>
				{% include "blog/post_dropdown.html" %}
			</div>
				<h2><a class="article-title" href="{% url 'post:post-detail' post.author post.id %}">{{ post.title}}</a></h2>
				<p class="article-content">{{ post.content }}</p>
				{% if post.image %}
					<img src="{{post.image.url}}" class=" rounded img-fluid mb-4" alt="...">
				{% endif %}
				{% include "blog/post_activities.html" %}
		</div>
	</article>
{% endfor %}
	<!-- is_paginated is a variable available from the paginator object in the PostListView -->
	{% if is_paginated %}
		<!-- if codeblock to display the first and previous pages as a button -->
		{% if page_obj.has_previous %}
			<a class="btn btn-outline-info mb-4" href="?page=1">First</a>
			<a class="btn btn-outline-info mb-4" href="?page={{ page_obj.previous_page_number }}">Previous</a>
		{% endif %}

		{% for num in page_obj.paginator.page_range %}
			{% if page_obj.number == num %}
				<a class="btn btn-info mb-4" href="?page={{ num }}">{{ num }}</a>
			{% elif num > page_obj.number|add:'-3' and num < page_obj.number|add:'3' %}
				<a class="btn btn-outline-info mb-4" href="?page={{ num }}">{{ num }}</a>
			{% endif %}
		{% endfor %}

		{% if page_obj.has_next %}
			<a class="btn btn-outline-info mb-4" href="?page={{ page_obj.next_page_number}}">Next</a>
			<a class="btn btn-outline-info mb-4" href="?page={{ page_obj.paginator.num_pages }}">Last</a>
		{% endif %}
	{% endif %}
{% endblock content %}

activity/templates/activity/bookmarks.html
{% extends "blog/sidebar.html" %}

{% block content %}
	<h4 class="mb-4">Bookmarks</h4>
	{% for activity in bookmark_activity %}
	<article class="media content-section mt-3">
			<img class="rounded-circle article-img" src="{{ activity.author.profile.image.url }}">
			<div class="media-body">
				<div class="article-metadata">
					<a href="{% url 'post:user-posts' activity.author.username %}"> {{ activity.author }}</a>
					<small class="text-muted ml-2">{{ activity.date_posted | timesince }} ago</small>
					<a class="ml-4" href="#">XXX</a>
					{% if user == activity.author %}
						<ul class="dropdown">
							<div class="dropdown edit-elipsis">
						       <a class="nav-link dropdown-toggle" href="#" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"></a> <span class="caret"></span>
						        <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
						          <a class="dropdown-item" href="{% url 'activity:activity-update' activity.id activity.slug %}">Edit</a>
						          <a class="dropdown-item" href="{% url 'activity:activity-delete' activity.id activity.slug %}">Delete</a>
						          <a class="dropdown-item" href="#">Something else here</a>
						        </div>
						 	</div>
						</ul>
					{% endif %}
			 	</div>
			 	<div class="article-metadata">
					<h4>{{ activity.name}}</h4>
					<p class="article-content">{{ activity.description }}</p>
				</div>
				<p><a href="{% url 'activity:activitypost-detail' activity.author activity.id activity.slug %}">View all posts in {{activity.name}}</a></p>
			</div>
		</article>

	{% empty %}
		<h5> You have no bookmarked activity. </h5>
{% endfor %}
{% endblock content %}