activity/urls.py
from django.urls import path
from .views import (ActivityListView, ActivityDeleteView, 
    ActivityDetailView, ActivityUpdateView, ActivityPostListView)
from . import views

"""this file maps all our urls and displays them 
   path contains the arguments(url link, httpResponse(function in views.py), alias for url)
"""

app_name = "activity"
urlpatterns = [
    path('user/<str:username>/activity/', ActivityListView.as_view(), name='activity-list'),
    path('activity/new/', views.CreateActivity, name='activity-create'),
    path('activity/<int:pk>/', ActivityDetailView.as_view(), name='activity-detail'),
    path('<str:username>/<int:pk>/<slug:slug>/', ActivityPostListView.as_view(), name='activitypost-detail'),
    path('bookmark_activity/<int:pk>', views.bookmark_activity, name='bookmark-activity'),
    path('activity/bookmarks/', views.bookmarks, name='bookmark-list'),
    path('activity/<int:pk>/<slug:slug>/update/', ActivityUpdateView.as_view(), name='activity-update'), 
    path('activity/<int:pk>/<slug:slug>/delete/', ActivityDeleteView.as_view(), name='activity-delete')
]

blog/urls.py
from django.urls import path
from .views import (PostDetail, 
	PostUpdateView, PostDeleteView,
	IndexView)

from . import views

"""this file maps all our urls and displays them 
   path contains the arguments(url link, httpResponse(function in views.py), alias for url)
"""
app_name = "post"

urlpatterns = [
	path('', IndexView.as_view(), name='index-home'),
    path('home', views.home, name='blog-home'), 
    # path('post/new/', PostCreateView.as_view(), name='post-create'),
    path('user/<str:username>/', views.UserPosts, name='user-posts'),
    # path('user/<str:username>/', PostListActivityView.as_view(), name='user-posts'), 
    path('post/<str:username>/<int:pk>/', views.PostDetail, name='post-detail'),
    path('create-post/', views.createPost, name='create-post'),
    path('post/<int:pk>/update/', PostUpdateView.as_view(), name='post-update'), 
    path('post/<int:pk>/delete/', PostDeleteView.as_view(), name='post-delete'),
    path('favorite/',views.favorite_post, name='favorite-post'), 
    path('<str:username>/favorites/', views.user_favorites, name='favorites_list'),
    path('like/',views.like_post, name='like-post'), 
    path('about', views.about, name='blog-about'),
    path('userssearch/', views.userSearch, name='search-users')
]

projectActivity/urls.py
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from users import views as user_views #import the user views directly here rather than use include
from users.views import LoginView, registerProfile



urlpatterns = [
    path('admin/', admin.site.urls),
    path('register/', user_views.register, name="register"),
    path('create/profile', registerProfile, name='signup_profile'),
    path('profile/edit/', user_views.profile, name="edit-profile"),
    # this is a class-based view (as_view is a function that directs where the url should look for the template)
    path('login/', LoginView.as_view(), name="login"),
    path('logout/', auth_views.LogoutView.as_view(template_name='users/logout.html'), name="logout"),
    path('password-reset/', 
        auth_views.PasswordResetView.as_view(
            template_name='users/password_reset.html'), name="password_reset"
        ),
    path('password-reset/done/', 
        auth_views.PasswordResetDoneView.as_view(
            template_name='users/password_reset_done.html'), name="password_reset_done"
        ),
    path('password-reset-confirm/<uidb64>/<token>/', 
        auth_views.PasswordResetConfirmView.as_view(
            template_name='users/password_reset_confirm.html'), name="password_reset_confirm"
        ),
    path('password-reset-complete/', 
        auth_views.PasswordResetCompleteView.as_view(
            template_name='users/password_reset_complete.html'), name="password_reset_complete"
        ),
    path('', include('blog.urls')), #the include function processes the url and sends to the blogs url file for processing.
    path('', include('activity.urls')),
    path('', include('comments.urls')),
    path('', include('relationships.urls')),
    path('api/', include('activity.api.urls')),
    path('notifications/', include('notify.urls', namespace='notifications')),
    path('api-auth/', include('rest_framework.urls')),

]
#leaving the url string empty makes it the default home page i.e localhost:8000

#Deloying static files during development
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

relationships/urls.py
from django.urls import path
from .views import UsersDisplayListView, FollowersDisplayListView, FollowingUserDisplayListView
from .import views 

app_name = "relationship"

urlpatterns = [
	path('follow/<str:username>', views.follow, name='follow_user'),
	path('unfollow/<str:username>', views.unfollow, name='unfollow_user'),
	path('users/list', UsersDisplayListView.as_view(), name='user-list'),
	path('find-and-add/', views.find_and_add, name='find_add_user'),
	path('<str:username>/followers', FollowersDisplayListView.as_view(), name='followers-list'),
	path('<str:username>/following', FollowingUserDisplayListView.as_view(), name='following-list')

]

urls.py
try:
    from django.conf.urls import url
except ImportError:
    from django.urls import url

from notify import views as nf

app_name = 'notifications'


urlpatterns = [
    url(r'^all/$', nf.notifications, name="all"),
    url(r'^api/update/$', nf.notification_update, name="update"),
    url(r'^mark/$', nf.mark, name='mark'),
    url(r'^mark-all/$', nf.mark_all, name='mark_all'),
    url(r'^delete/$', nf.delete, name='delete'),
    url(r'^rdr/(?P<notification_id>[\d]+)/$', nf.read_and_redirect,
        name='read_and_redirect'),
]

comments/models.py
from django.db import models
from django.utils import timezone
from blog.models import Post
from django.contrib.auth.models import User
from django.urls import reverse
# Create your models here.

class Comment(models.Model):
	author 		= models.ForeignKey(User, on_delete=models.CASCADE)
	post 		= models.ForeignKey(Post, on_delete=models.CASCADE)
	content 	= models.TextField()
	# slug 		= models.SlugField(max_length=50, unique=True, null=True)
	image		= models.ImageField(null=True, upload_to='post_pics', blank=True)
	likes		= models.ManyToManyField(User, related_name='comment_likes', blank=True)
	date_posted = models.DateTimeField(default=timezone.now)
	parent 		= models.ForeignKey('self', on_delete=models.CASCADE, null=True, blank=True, related_name='replies')


	def __str__(self):
		return self.content[:80]

	def get_absolute_url(self):
		return reverse('post:user-posts', kwargs={'username': self.author})

post/models.py
from django.db import models

# Create your models here.

relationships/forms.py
from django import forms
from .models import Relationship


class SearchForm(forms.Form):
	q = forms.CharField(label='', max_length=50)

blog/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from django.views.generic import ListView, DetailView, CreateView, UpdateView, DeleteView, FormView
from django.views.generic.edit import FormMixin
from django.http import HttpResponseRedirect, HttpResponse, JsonResponse
from django.views import View
from django.template.loader import render_to_string 
from .models import Post
from comments.forms import CommentForm
from activity.models import Activity
from relationships.models import Relationship
from relationships.util import get_people_user_follows
from comments.models import Comment
from users.forms import UserLoginForm
from django.contrib.auth.views import LoginView
from .forms import PostForm
from relationships.forms import SearchForm
from django.urls import reverse
from activity.views import ActivityPostListView
from itertools import chain
from operator import attrgetter
from notify.signals import notify
from dal import autocomplete
import json
#from django.http import HttpResponse
# Create your views here.

@login_required
def home(request):
	"""this function renders the home html template in templates directory(using the render import)"""

	user_followers = Relationship.objects.filter(from_user=request.user).values_list('to_user', flat=True)
	user_following = Relationship.objects.filter(to_user=request.user).values_list('from_user', flat=True)
	posts = Post.objects.filter(author_id__in=user_followers).order_by('-date_posted') | Post.objects.filter(author=request.user).order_by('-date_posted') | Post.objects.filter(author_id__in=user_following).order_by('-date_posted')#query's the database for the all the posts
	users = User.objects.all().order_by('-date_joined')[:6]
	#user = get_object_or_404(User, username=request.user)
	user_posts = posts.filter(author=request.user).count()
	user_activity  = Activity.objects.filter(author=request.user).count()
	user_following = Relationship.objects.filter(from_user=request.user).count()
	user_followers = Relationship.objects.filter(to_user=request.user).count()

	search_form = SearchForm

	return_list = []
	for post in posts:
		return_list.append((post, Post.objects.filter(id=post.id, likes__username=request.user.username), 
			Post.objects.filter(id=post.id, favorite__username=request.user.username)))

	# is_favorite = posts.filter(favorite__username=request.user.username).values_list('id', flat=True)
	# is_liked	= posts.filter(likes__username=request.user.username).values_list('id', flat=True)
	
	# activities = Activity.objects.all()
	# result_list = sorted(chain(posts, activities), key=attrgetter('date_posted'), reverse=True)
	# filter(author_id__in=following)

	if request.method == 'POST':
		form = PostForm(request.user, request.POST, request.FILES)
		if form.is_valid():
			post = form.save(commit=False)
			post.author = request.user
			post.activity_id = form.cleaned_data['activity'].pk
			post.save()
			return redirect('post:blog-home')
	else:
		form = PostForm(user=request.user)

	context = {
		'posts': return_list, #query's the database for the all the posts
		'users': users,
		# 'activities': Activity.objects.all().order_by('-date_posted'),
		# 'posts': result_list,
		'form': form,
		'posts_count': user_posts,
		'activities_count': user_activity,
		'following_count' : user_following,
		'followers_count' : user_followers,
		# 'is_liked': is_liked,
		# 'is_favorite': is_favorite,
		'search_form': search_form
	}
	return render(request, 'blog/home.html', context);


#this function renders the about html template in templates directory
class IndexView(LoginView):
	template_name = 'users/index_login.html'
	form_class = UserLoginForm

#this function renders the about html template in templates directory
def about(request):
	return render(request, 'blog/about.html', {'title': 'About'});


# class PostListView(ListView):
# 	"""A class-based view to display the posts in a list view
# 	the class is inherited from the listview view class of django
# 	django expects to look for the template in this pattern(#<app>(name of the app)/<model>(model name)_<viewtype>(type of view i.e create, detail).html)
# 	"""
# 	model = Post # model to be affected
# 	template_name = 'blog/home.html' #<app>/<model>_<viewtype>.html
# 	context_object_name = 'posts' #by default it expects the context to be called object here it is changed to posts as above.
# 	ordering = ['-date_posted'] #this orders the post in ascending order (most recent post to older post)
# 	paginate_by = 5 #reduces the amount of posts displayed per page

	# def get_queryset(self):
	# 	qs1 = Post.objects.all()
	# 	qs2 = Activity.objects.all()
	# 	queryset = sorted(chain(qs1, qs2), key=attrgetter('date_posted'),reverse=True)
	# 	return queryset

	# def get_context_data(self, **kwargs):
	# 	context = super(PostListView, self).get_context_data(**kwargs)
	# 	# posts = Post.objects.all()
	# 	context['activities'] = Activity.objects.all()
	# 	# context['queryset'] = sorted(chain(posts, activities), key=attrgetter('date_posted'), reverse=True)
	# 	return context

# class UserPostListView(ListView, FormMixin):
# 	model = Post # model to be affected
# 	template_name = 'blog/user_posts.html' #<app>/<model>_<viewtype>.html
# 	context_object_name = 'posts' #by default it expects the context to be called object here it is changed to posts as above.
# 	paginate_by = 8 #reduces the amount of posts displayed per page
# 	slug_field = 'user__username'
# 	slug_url_kwarg = 'username'
# 	form_class = PostForm
# 	ordering = '-date_posted'

# 	def get_queryset(self):
# 		""" the get_queryset method(from the class listview)here is overriden to return the username in the url pattern
# 		username=self.kwargs.get('username') gets the username from the url or returns a 404(does not exist)
# 		"""
# 		user = get_object_or_404(User, username=self.kwargs['username']) 
# 		return Post.objects.filter(author=user).order_by('-date_posted') # the post model object is filtered to return only posts from a certain  user
	
# 	def get_context_data(self, **kwargs):
# 		""" the get_context_data function of the listview class is overriden to return an instance of the user object """

# 		context = super(UserPostListView, self).get_context_data(**kwargs) 
# 		user = get_object_or_404(User, username=self.kwargs.get('username')) #get the username from the url
# 		posts = Post.objects.filter(author=user).count()
# 		activities = Activity.objects.filter(author=user).count()
# 		following  = Relationship.objects.filter(from_user=user).count()
# 		followers  = Relationship.objects.filter(to_user=user).count()
# 		context['posts_count'] = posts
# 		context['activities_count'] = activities
# 		context['following_count'] = following
# 		context['followers_count'] = followers
# 		context['user_profile'] = user #saves the user object as user_profile
# 		context['is_favorite'] = Post.objects.filter(favorite__username=self.request.user.username).values_list('id', flat=True)
# 		context['is_liked'] = Post.objects.filter(likes__username=self.request.user.username).values_list('id', flat=True)
# 		return context

# 	def get_form_kwargs(self):
# 		kwargs = super(UserPostListView,self).get_form_kwargs()
# 		kwargs.update({'user': self.request.user})
# 		return kwargs

def PostDetail(request, pk, username): 
	"""
	a view function to display a post in detail with all its comments and replies
	a comment form is also passed for a user to leave a comment
	"""
	post = get_object_or_404(Post, pk=pk) #get a single post using its pk
	user = get_object_or_404(User, username=username)
	is_favorite = False
	is_liked	= False
	comment_like= False

	if post.likes.filter(pk=request.user.id).exists():
		is_liked = True

	if post.favorite.filter(pk=request.user.id).exists():
		is_favorite = True 

	# filter the comment model returning all comments associated with an individual post 
	comment_post = Comment.objects.filter(post=pk, parent__isnull=True).order_by('date_posted') 

	comment_like = comment_post.filter(likes__username=request.user.username).values_list('id', flat=True)

	if request.method == 'POST':
		comment_form = CommentForm(request.POST, request.FILES or None)
		if comment_form.is_valid():
			Parent_obj = None
			try:
				Parent_id = int(request.POST.get('parent_id')) #get the id of the form 
			except:
				Parent_id = None
			if Parent_id: 
				Parent_obj = Comment.objects.get(id=Parent_id) #get the parent obj from the comment model passing in the id value
				if Parent_obj:
					reply_comment = comment_form.save(commit=False) #saves the comment as a reply to another comment on the main post not as a comment on the main post
					reply_comment.author = request.user #saves the author object as the logged in user
					reply_comment.parent = Parent_obj # saves the comment as a reply
					# return redirect('comment:reply-thread', Parent_obj.id)
			comment = comment_form.save(commit=False) # if no parent id is gotten save the comment as a new comment to the main post 
			comment.author = request.user # save username of the logged in user
			comment.post = post # saves the pk of the current post 
			comment.content = comment_form.cleaned_data.get('content')
			# comment.image = comment_form.cleaned_data.get('image')
			notify.send(request.user, recipient=user, actor=request.user, 
				verb='commented on your post', obj=comment.post, nf_type='comment_by_user')
			comment.save()
			parts = comment.content.split()
			for index, value in enumerate(parts):
					if value.startswith("@"):
						results = value[1:]
						try:
							user = User.objects.get(username=results)
							notify.send(request.user, recipient=user, actor=request.user, 
								verb='mentioned you in a comment', target=comment, nf_type='mentioned_comment_by_user')
						except user.DoesNotExist: 

post/views.py
from django.shortcuts import render

# Create your views here.

blog/templates/blog/about.html
{% extends "blog/base.html"%}
{% block content %}
	<h1>About Page</h1>
{% endblock content %}

blog/templates/blog/follow_button.html
{% extends "blog/user_posts.html" %}
{% load relationship_tags %}

{% friends_for_user user as friend_dict %}
	{% dict_entry_for_item user_profile.username from friend_dict as friend %}
		{% if user_profile != request.user %}
			<form method="POST" action="{% if friend %}{% url 'relationship:unfollow_user' view.kwargs.username %} {% else %} {% url 'relationship:follow_user' view.kwargs.username %} {% endif %}">
		  		{% csrf_token %}
				<button class="btn btn-outline-primary">{% if friend %}Unfollow{% else %}Follow{% endif %}</button>
			</form>
		{% endif %}

blog/templates/blog/header.html
<header class="site-header">
	<nav class="navbar navbar-expand-md navbar-dark bg-steel fixed-top">
	    <div class="container">
	          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarToggle" aria-controls="navbarToggle" aria-expanded="false" aria-label="Toggle navigation">
	          <span class="navbar-toggler-icon"></span>
	          </button>
	        {% if user.is_authenticated %}
	        	<a class="navbar-brand mr-4" href="{% url 'post:blog-home' %}">Django Blog</a>
	        {% else %}
	        	<a class="navbar-brand mr-4" href="{% url 'post:index-home' %}">Django Blog</a>
	        {% endif %}

	        <div class="collapse navbar-collapse" id="navbarToggle">
	            <div class="navbar-nav mr-auto">
	              {% block search_form %} {% endblock search_form %}
	            </div>
	            <!-- Navbar Right Side -->
	            <div class="navbar-nav">
	            	{% if user.is_authenticated %}
	            	{% include "blog/user_search.html" %}
					 <a href="{% url 'notifications:all' %}" class="nav-item nav-link">Notifications</a>
					 <img src="{{ user.profile.image.url }}" class="rounded-circle nav-img" alt="...">
	            		<div class="dropdown">
  							<a class="nav-link dropdown-toggle" data-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false">{{ user.profile.last_name }}</a>
  							<div class="dropdown-menu" aria-labelledby="dropdownMenuLink">
  								<a class="dropdown-item" href="{% url 'post:user-posts' request.user %}">View Profile</a>
    							<a class="dropdown-item" href="{% url 'edit-profile' %}">Edit Profile</a>
    							<div class="dropdown-divider"></div>
    							<a class="dropdown-item" href="#">Help</a>
    							<a class="dropdown-item" href="{% url 'post:blog-about' %}">About</a>
    							<div class="dropdown-divider"></div>
    							<a class="dropdown-item" href="{% url 'logout' %}">Logout</a>
  							</div>
						</div>
	            	{% else %}
		              	<a class="nav-item nav-link" href="{% url 'login' %}">Login</a>
		              	<a class="nav-item nav-link" href="{% url 'register' %}">Register</a>
		            {% endif %}
	            </div>
	        </div>
	    </div>
	</nav>
</header>

blog/templates/blog/home.html
<!-- imports the base file here -->
<!-- displays the the block contents in this html in the block content of base.html file -->
{% extends "blog/base.html"%}
{% load crispy_forms_tags %}

{% block usersidebar %}
{% include "blog/home_right_sidebar.html" %}
{% endblock usersidebar %}

{% comment %}
{% block search_form %}
	<form class="form-inline" method="GET">
		<div class="col-7">
	   		<input  class="form-control mr-sm-2" type="text" name="q" value="testuser" maxlength="50" class="textinput textInput form-control" required="" id="id_q" placeholder="Search for users by their username">
	   	</div>
	   	<div class="col">
			<button class="btn btn-outline-light my-2 my-sm-0">Search</button>
		</div>
	</form>
{% endblock search_form %}
{% endcomment %}

{% block content %}
	<div class="content-section">
		<form method="POST" enctype="multipart/form-data">
			{% csrf_token %}
			<fieldset class="form-group">
				{{ form|crispy }}
			
			<div class="form-group">
				<button class="btn btn-outline-info" type="submit">Post</button>
			</div></fieldset>
		</form>
	</div>
	{% for post, is_liked, is_favorite in posts %}
			<article class="media content-section">
			   <img class="rounded-circle article-img" src="{{ post.author.profile.image.url }}">
			   <div class="media-body">
					<div class="article-metadata">
						<a href="{% url 'post:user-posts' post.author.username %}"> {{ post.author }}</a>
						<small class="text-muted">{{ post.date_posted|timesince}} ago</small>
						{% include "blog/post_dropdown.html" %}
			 		</div>
					<small class="text-muted pt-6">Posted in<a href="{% url 'activity:activitypost-detail' post.author post.activity.id post.activity.slug %}"> {{ post.activity }}</a></small>
						{% if post.content|length > 40 %}
							<p class="article-content">{{ post.content| truncatewords:40}} <a href="{% url 'post:post-detail' post.author post.id %}">read more</a></p>
						{% else %}
							<p class="article-content">{{ post.content }}</p>
						{% endif %}
						{% if post.image %}
							<img src="{{post.image.url}}" class="rounded img-fluid mb-4" alt="...">
						{% endif %}
						<div class="row">
							<div class="col-3" id="{{ post.id}}">
								{% include "blog/post_like_button.html" %}
							</div>
							<div class="col-4">
								<p><a href="{% url 'post:post-detail' post.author post.id %}">Comment ({{ post.comment_set.count }})</a></p>
							</div>
							<div class="col-4" id="{{ post.id}}">
								{% include "blog/post_favorite_button.html" %}
							</div>
						</div>
							<!-- <hr>
						<small class="font-weight-normal"><a href="{% url 'post:post-detail' post.author post.id %}">View all comments and replies</a></small> -->
				</div>
			</article>
	{% endfor %}
{% comment %}
<!-- 	{% for activity in activities %}
		<article class="media content-section mt-3">
			<img class="rounded-circle article-img" src="{{ activity.author.profile.image.url }}">
			<div class="media-body">
					<div class="article-metadata">
						<a href="{% url 'post:user-posts' activity.author.username %}"> {{ activity.author }}</a>
						<small class="text-muted ml-2">{{ activity.date_posted}} </small>
						{% if user == activity.author %}
							<div class="edit-elipsis" id="navbarNavDropdown">
							    <ul class="navbar-nav">
								    <li class="nav-item dropdown">
								        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"><i class="fas fa-ellipsis-h"></i></a>
								        <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
								          <a class="dropdown-item" href="{% url 'activity:activity-update' activity.id %}">Edit</a>
								          <a class="dropdown-item" href="{% url 'activity:activity-delete' activity.id %}">Delete</a>
								        </div>
								    </li>
							    </ul>
						 	</div>
						{% endif %}
			 		</div>
					<h4><a class="article-title" href="{% url 'activitypost-detail' activity.author activity.id %}">{{ activity.name}}</a></h4>
					<p class="article-content">{{ activity.description }}</p>
					<p class="article-content">{{ activity.target }}</p>
			</div>
		</article>
	{% endfor %} -->
{% endcomment %}
	<!-- is_paginated is a variable available from the paginator object in the PostListView -->
	{% if is_paginated %}
		<!-- if codeblock to display the first and previous pages as a button -->
		{% if page_obj.has_previous %}
			<a class="btn btn-outline-info mb-4" href="?page=1">First</a>
			<a class="btn btn-outline-info mb-4" href="?page={{ page_obj.previous_page_number }}">Previous</a>
		{% endif %}

		{% for num in page_obj.paginator.page_range %}
			{% if page_obj.number == num %}
				<a class="btn btn-info mb-4" href="?page={{ num }}">{{ num }}</a>
			{% elif num > page_obj.number|add:'-3' and num < page_obj.number|add:'3' %}
				<a class="btn btn-outline-info mb-4" href="?page={{ num }}">{{ num }}</a>
			{% endif %}
		{% endfor %}

		{% if page_obj.has_next %}
			<a class="btn btn-outline-info mb-4" href="?page={{ page_obj.next_page_number}}">Next</a>
			<a class="btn btn-outline-info mb-4" href="?page={{ page_obj.paginator.num_pages }}">Last</a>
		{% endif %}
	{% endif %}
{% endblock content %}

blog/templates/blog/home_right_sidebar.html
{% load relationship_tags %}

    <div class="d-none d-lg-block mb-4">
  		<div class="card text-center">
  			<div class="card-body">
  				<img class="rounded article-img" src="{{ request.user.profile.image.url }}">
    			<h6 class="card-title mt-2 text-muted">{{request.user.profile.first_name}} {{request.user.profile.last_name}}<BR>
    				<span><a href="{% url 'post:user-posts' request.user.username %}">@{{request.user.username}}</a></span>
    			</h6>
    			<hr>
    			<p class="card-text">{{ request.user.profile.bio | truncatewords:20}}</p>
    			<hr>
    			<div class="row justify-content-between">
    				<div class="ml-4">
    					<a href="{% url 'post:user-posts' user.username %}"><span class="badge badge-primary badge-pill">{{ posts_count }}</span><BR><span class="text-muted">Posts</span></a>
    				</div>
    				<div>
    					<a href="{% url 'relationship:followers-list' user.username %}"><span class="badge badge-primary badge-pill">{{ followers_count }}</span><BR><span class="text-muted">Followers</span></a>
    				</div>
    				<div>
    					<a href="{% url 'relationship:following-list' user.username %}"><span class="badge badge-primary badge-pill">{{ following_count }}</span><BR><span class="text-muted">Following</span></a>
    				</div>
    			</div>
  			</div>
		</div>
	</div>
<div class="d-none d-lg-block mb-4">
	<ul class="d-none d-lg-block list-group">
	    <li class="list-group-item"><h6>New users</h6></li>
  	</ul>
  	{% friends_for_user user as friend_dict %}
		{% for user in users %}
			{% dict_entry_for_item user.username from friend_dict as friend %}
				<ul class="d-none d-lg-block list-group-item">
			    	<div class="d-flex w-100">
			      		<img class="rounded-circle newusers-img" src="{{ user.profile.image.url }}">
			      		<h6><a href="{% url 'post:user-posts' user.username %}">{{ user.username }}</a></h6>
			      		{% if user != request.user %}
			      			<form method="POST" action="{% if friend %}{% url 'relationship:unfollow_user' user.username %} {% else %} {% url 'relationship:follow_user' user.username %} {% endif %}" style="margin-left: auto";>
							{% csrf_token %}
                    		<button class="btn btn-outline-primary btn-sm" >{% if friend %}Unfollow{% else %}Follow{% endif %}</button>
                			</form>
			      			<!-- <button type="button" class="newusers-btn btn btn-outline-primary btn-sm">Follow</button> -->
			      		{% endif %}
			    	</div>
		  		</ul>
		{% endfor %}
	<ul class="list-group">
	    <li class="list-group-item"><a href="{% url 'relationship:user-list' %}">View more...</a></li>
  	</ul>
 </div>

blog/templates/blog/post_activities.html
<div class="row">
	<div class="col-3" id="{{ post.id}}">
		{% include "blog/post_like_button.html" %}
	</div>
	<div class="col-4">
		<p><a href="{% url 'post:post-detail' post.author post.id %}">Comment ({{ post.comment_set.count }})</a></p>
	</div>
	<div class="col-4">
		{% if post.id in is_favorite %}
			<p><a href="{% url 'post:favorite-post' post.id %}">unfavorite ({{post.favorite.count}})</a></p>
		{% else %}
			<p><a href="{% url 'post:favorite-post' post.id %}">favorite ({{post.favorite.count}})</a></p>
		{% endif %}
	</div>
</div>

blog/templates/blog/post_favorite_button.html
{% if is_favorite %}
	<button type="submit" value="{{ post.id }}" class="favorite-button btn btn-danger">unfavorite ({{post.favorite.count}})</button>
{% else %}
	<button type="submit" value="{{ post.id }}" class="favorite-button btn btn-primary">favorite ({{post.favorite.count}})</button>
{% endif %}