activity/urls.py
from django.urls import path
from .views import (ActivityListView, ActivityDeleteView, 
    ActivityDetailView, ActivityUpdateView, ActivityPostListView)
from . import views

"""this file maps all our urls and displays them 
   path contains the arguments(url link, httpResponse(function in views.py), alias for url)
"""

app_name = "activity"
urlpatterns = [
    path('user/<str:username>/activity/', ActivityListView.as_view(), name='activity-list'),
    path('activity/new/', views.CreateActivity, name='activity-create'),
    path('activity/<int:pk>/', ActivityDetailView.as_view(), name='activity-detail'),
    path('<str:username>/<int:pk>/<slug:slug>/', ActivityPostListView.as_view(), name='activitypost-detail'),
    path('bookmark_activity/<int:pk>', views.bookmark_activity, name='bookmark-activity'),
    path('activity/bookmarks/', views.bookmarks, name='bookmark-list'),
    path('activity/<int:pk>/<slug:slug>/update/', ActivityUpdateView.as_view(), name='activity-update'), 
    path('activity/<int:pk>/<slug:slug>/delete/', ActivityDeleteView.as_view(), name='activity-delete')
]

blog/urls.py
from django.urls import path
from .views import (PostDetail, 
	PostUpdateView, PostDeleteView,
	IndexView)

from . import views

"""this file maps all our urls and displays them 
   path contains the arguments(url link, httpResponse(function in views.py), alias for url)
"""
app_name = "post"

urlpatterns = [
	path('', IndexView.as_view(), name='index-home'),
    path('home', views.home, name='blog-home'), 
    # path('post/new/', PostCreateView.as_view(), name='post-create'),
    path('user/<str:username>/', views.UserPosts, name='user-posts'),
    # path('user/<str:username>/', PostListActivityView.as_view(), name='user-posts'), 
    path('post/<str:username>/<int:pk>/', views.PostDetail, name='post-detail'),
    path('create-post/', views.createPost, name='create-post'),
    path('post/<int:pk>/update/', PostUpdateView.as_view(), name='post-update'), 
    path('post/<int:pk>/delete/', PostDeleteView.as_view(), name='post-delete'),
    path('favorite/',views.favorite_post, name='favorite-post'), 
    path('<str:username>/favorites/', views.user_favorites, name='favorites_list'),
    path('like/',views.like_post, name='like-post'), 
    path('about', views.about, name='blog-about'),
    path('userssearch/', views.userSearch, name='search-users')
]

projectActivity/urls.py
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from users import views as user_views #import the user views directly here rather than use include
from users.views import LoginView, registerProfile



urlpatterns = [
    path('admin/', admin.site.urls),
    path('register/', user_views.register, name="register"),
    path('create/profile', registerProfile, name='signup_profile'),
    path('profile/edit/', user_views.profile, name="edit-profile"),
    # this is a class-based view (as_view is a function that directs where the url should look for the template)
    path('login/', LoginView.as_view(), name="login"),
    path('logout/', auth_views.LogoutView.as_view(template_name='users/logout.html'), name="logout"),
    path('password-reset/', 
        auth_views.PasswordResetView.as_view(
            template_name='users/password_reset.html'), name="password_reset"
        ),
    path('password-reset/done/', 
        auth_views.PasswordResetDoneView.as_view(
            template_name='users/password_reset_done.html'), name="password_reset_done"
        ),
    path('password-reset-confirm/<uidb64>/<token>/', 
        auth_views.PasswordResetConfirmView.as_view(
            template_name='users/password_reset_confirm.html'), name="password_reset_confirm"
        ),
    path('password-reset-complete/', 
        auth_views.PasswordResetCompleteView.as_view(
            template_name='users/password_reset_complete.html'), name="password_reset_complete"
        ),
    path('', include('blog.urls')), #the include function processes the url and sends to the blogs url file for processing.
    path('', include('activity.urls')),
    path('', include('comments.urls')),
    path('', include('relationships.urls')),
    path('api/', include('activity.api.urls')),
    path('notifications/', include('notify.urls', namespace='notifications')),
    path('api-auth/', include('rest_framework.urls')),

]
#leaving the url string empty makes it the default home page i.e localhost:8000

#Deloying static files during development
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

relationships/urls.py
from django.urls import path
from .views import UsersDisplayListView, FollowersDisplayListView, FollowingUserDisplayListView
from .import views 

app_name = "relationship"

urlpatterns = [
	path('follow/<str:username>', views.follow, name='follow_user'),
	path('unfollow/<str:username>', views.unfollow, name='unfollow_user'),
	path('users/list', UsersDisplayListView.as_view(), name='user-list'),
	path('find-and-add/', views.find_and_add, name='find_add_user'),
	path('<str:username>/followers', FollowersDisplayListView.as_view(), name='followers-list'),
	path('<str:username>/following', FollowingUserDisplayListView.as_view(), name='following-list')

]

urls.py
try:
    from django.conf.urls import url
except ImportError:
    from django.urls import url

from notify import views as nf

app_name = 'notifications'


urlpatterns = [
    url(r'^all/$', nf.notifications, name="all"),
    url(r'^api/update/$', nf.notification_update, name="update"),
    url(r'^mark/$', nf.mark, name='mark'),
    url(r'^mark-all/$', nf.mark_all, name='mark_all'),
    url(r'^delete/$', nf.delete, name='delete'),
    url(r'^rdr/(?P<notification_id>[\d]+)/$', nf.read_and_redirect,
        name='read_and_redirect'),
]

users/models.py
from django.db import models
from django.contrib.auth.models import User
from PIL import Image
# Create your models here.

class Profile(models.Model):
	user = models.OneToOneField(User, on_delete=models.CASCADE)
	first_name = models.CharField(max_length=100)
	last_name  = models.CharField(max_length=100)
	GENDER = (('M', 'Male'), ('F', 'Female'), ('O', 'Other'), )
	gender = models.CharField(max_length=50, choices=GENDER, default=None, null=True)
	location = models.CharField(max_length=50)
	bio = models.TextField()

	#default.jpg(default image of users without a picture) upload_to(folder where uploaded images are stored).
	image = models.ImageField(default='default.jpg', upload_to='profile_pics')

	def __str__(self):
		return f'{self.user.username} Profile' #formatted string to display username 

	#this save function resizes the image uploaded by the user to the user profile.
	def save(self, *args, **kwargs):
		super(Profile, self).save(*args, **kwargs) #run the save method of parent class(profile)

		img = Image.open(self.image.path)

		if img.height > 300 and img.width > 300: #checks the height and width of the image 
			output_size = (300, 300)
			img.thumbnail(output_size)
			img.save(self.image.path)

users/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from .models import Profile

#UserCreationForm is inherited in this class. This helps us extend the usercreation form to add other fields i.e email
class UserRegisterForm(UserCreationForm):
	email = forms.EmailField(required=True)

	#this class function takes the username and converts it to a lower case insensitive char and saves to the database 
	def clean_username(self):
		data = self.cleaned_data['username']
		return data.lower()

	#the meta class makes it possible to edit the UserCreationForm with more fields 
	class Meta:
		model = User # User model to be affected 
		fields = ['username', 'email', 'password1', 'password2']

	def clean_email(self):
		email = self.cleaned_data['email']
		username = data = self.cleaned_data['username']
		# print User.objects.filter(email=email).count()
		if email and User.objects.filter(email__iexact=email).exists():
			raise forms.ValidationError('This email address is already registered.')
		return email


""" UserLoginForm inherits from the django AuthenticationForm 
done here in other to changed the cleaned username to lower the case to authenticate the user(for now). 
"""
class UserLoginForm(AuthenticationForm):

	class Meta:
		model = User
		fields = ['username', 'password']

	def clean_username(self):
		data = self.cleaned_data['username']
		return data.lower() #converts the username to lower case for authenticaton.

#this class helps to update the user model form i.e editing the username and email
class UserUpdateForm(forms.ModelForm):
	email = forms.EmailField()

	#the meta class makes it possible to edit update the fields in user form
	class Meta:
		model = User # User model to be affected 
		fields = ['username', 'email']

	def clean_username(self):
		data = self.cleaned_data['username']
		return data.lower() 

#this class helps to update the profile model form i.e editing the image field
class ProfileUpdateForm(forms.ModelForm):
	#the meta class makes it possible to edit update the fields in profile form
	class Meta:
		model = Profile # Profile model to be affected 
		fields = ['first_name','last_name','gender','location','bio','image']

#this class displays the profile form to be updated by the user. 
class CreateProfileForm(forms.ModelForm):
	first_name = forms.CharField(required=True)
	last_name = forms.CharField(required=True)
	GENDER_SELECT = [('M', 'Male'), ('F', 'Female'), ('O', 'Other'), ]
	gender = forms.ChoiceField(choices=GENDER_SELECT, widget=forms.RadioSelect())

	class Meta: 
		model = Profile
		fields = ['first_name', 'last_name', 'gender']
		# GENDER_SELECT = (('M', 'Male'), ('F', 'Female'), ('O', 'Other'), )
		# widgets = {'gender': forms.RadioSelect(choices=GENDER_SELECT)}

users/views.py
from django.shortcuts import render, redirect
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from .forms import UserRegisterForm, UserUpdateForm, ProfileUpdateForm, UserLoginForm, CreateProfileForm
from django.contrib.auth import authenticate, login
from django.contrib.auth.views import LoginView
# Create your views here.

def register(request):
	if request.method == 'POST':
		form = UserRegisterForm(request.POST) #UserRegisterForm(subclassed form of UserCreationForm which is an auto-generated form from python)
		if form.is_valid():
			new_user = form.save()
			username = form.cleaned_data.get('username')
			login(request, new_user) # the user is automatically logged in after registration
			return redirect('signup_profile') #redirects to the create profile page
	else:
		form = UserRegisterForm() #UserRegisterForm is an auto-generated form from python

	return render(request, 'users/register.html', {'form': form})


"""
the UserUpdateForm and the UserRegisterForm are populated with the user data(instance=request.user)

and the data to be posted(request.POST)

the request.FILES sends the image contained in the post to the ProfileUpdateForm
"""
@login_required #this a decorator(a decorator adds functionality to an existing function)
def profile(request):
	if request.method == 'POST':
		u_form = UserUpdateForm(request.POST, instance=request.user) #we instantiate the UserUpdateForm in order to use it in the template
		p_form = ProfileUpdateForm(request.POST, request.FILES, instance=request.user.profile)

		if u_form.is_valid() and p_form.is_valid():
			u_form.save()
			p_form.save()
			messages.success(request, f'Your account has been updated')
			return redirect('edit-profile') #redirects to the profile page
	else:
		u_form = UserUpdateForm(instance=request.user) #we instantiate the UserUpdateForm in order to use it in the template
		p_form = ProfileUpdateForm(instance=request.user.profile)

	#pass the instance so we can render it in the template
	context = {
		'u_form': u_form,
		'p_form': p_form
	}
	return render(request, 'users/editprofile.html', context)

"""
this LoginView function subclasses the LoginView class based view of django.

done here in other to use the UserLoginForm which is a subclass of the django AuthenticationForm
"""	
class LoginView(LoginView):
	template_name = 'users/login.html'
	form_class = UserLoginForm

"""
this function view takes care of updating the user's profile after registration
"""
@login_required
def registerProfile(request):
	if request.method == 'POST':
		form = CreateProfileForm(request.POST, instance=request.user.profile)
		if form.is_valid():
			form.save()
			messages.success(request, f'Your account has been created')
			return redirect('post:blog-home') # redirects to the homepage on success.
	else:
		form = CreateProfileForm()

	return render(request, 'users/signup_profile.html', {'form': form})

users/templates/users/editprofile.html
{% extends "blog/base.html"%}
{% load crispy_forms_tags %}
{% block content %}
	<div class="content-section">
		<div class="media">
			<img class="rounded-circle account-img" src="{{ user.profile.image.url }}">
			<div class="media-body">
				<h2 class="account-heading">{{ user.username }}</h2>
				<p class="text-secondary">{{ user.email }}</p>
			</div>
		</div>
		<!-- multipart/form-data helps to save the image correctly in the database -->
		<form method="POST" enctype="multipart/form-data">
			{% csrf_token %}
			<fieldset class="form-group">
				<legend clas="border-bottom mb-4">Profile Info</legend>
				{{ u_form|crispy }}
				{{ p_form|crispy }}
			</fieldset>
			<div class="form-group">
				<button class="btn btn-outline-info" type="submit">Update</button>
			</div>
		</form>
	</div>
{% endblock content %}

users/templates/users/index_login.html
{% extends "blog/index.html"%}
{% load crispy_forms_tags %}

{% block content %}
<div class="col-md-6 col-sm-12 col-lg-6">
	<h1 class="text-uppercase text-center text-md-left main-text">Start Something Creative...</h1>
	<h4 class="text-center text-md-left text-color">and share your journey with a community of people willing to offer you help and support.</h4>
</div>

<div class="col-md-6 col-sm-12 col-lg-5 pt-sm-4">
	<div class="content-section">
		<form method="POST">
			{% csrf_token %}
			<fieldset class="form-group">
				<legend clas="border-bottom mb-4">Log In</legend>
				{{ form|crispy }}
			</fieldset>
			<div class="form-group">
				<button class="btn btn-outline-info" type="submit">Log In</button>
				<small class="text-muted ml-2">
					<a href="{% url 'password_reset' %}">Forgot password?</a>
				</small>
			</div>
		</form>
		<div class="border-top pt-3">
			<small class="text-muted">
				Need An Account? <a href="{% url 'register' %}" class=""ml-2>Sign Up Now</a>
			</small>
		</div>
	</div>
</div>
{% endblock content %}

users/templates/users/login.html
{% extends "blog/base.html"%}
{% load crispy_forms_tags %}

{% block content %}
	<div class="content-section">
		<form method="POST">
			{% csrf_token %}
			<fieldset class="form-group">
				<legend clas="border-bottom mb-4">Log In</legend>
				{{ form|crispy }}
			</fieldset>
			<div class="form-group">
				<button class="btn btn-outline-info" type="submit">Log In</button>
				<small class="text-muted ml-2">
					<a href="{% url 'password_reset' %}">Forgot password?</a>
				</small>
			</div>
		</form>
		<div class="border-top pt-3">
			<small class="text-muted">
				Need An Account? <a href="{% url 'register' %}" class=""ml-2>Sign Up Now</a>
			</small>
		</div>
	</div>
{% endblock content %}

users/templates/users/logout.html
{% extends "blog/base.html"%}
{% load crispy_forms_tags %}
{% block content %}
	<h2>You have been logged out</h2>
		<div class="border-top pt-3">
			<small class="text-muted">
				<a href="{% url 'login' %}" class=""ml-2>Log In Again</a>
			</small>
		</div>

{% endblock content %}

users/templates/users/password_reset.html
{% extends "blog/base.html"%}
{% load crispy_forms_tags %}
{% block content %}
	<div class="content-section">
		<form method="POST">
			{% csrf_token %}
			<fieldset class="form-group">
				<legend clas="border-bottom mb-4">Reset Password</legend>
				{{ form|crispy }}
			</fieldset>
			<div class="form-group">
				<button class="btn btn-outline-info" type="submit">Request Password Reset</button>
			</div>
		</form>
	</div>
{% endblock content %}

users/templates/users/password_reset_complete.html
{% extends "blog/base.html"%}
{% load crispy_forms_tags %}
{% block content %}
	<div class="alert alert-info">
		Your password has been set.
	</div>
	<a href="{% url 'login' %}">Sign In Here</a>
{% endblock content %}

users/templates/users/password_reset_confirm.html
{% extends "blog/base.html"%}
{% load crispy_forms_tags %}
{% block content %}
	<div class="content-section">
		<form method="POST">
			{% csrf_token %}
			<fieldset class="form-group">
				<legend clas="border-bottom mb-4">Reset Password</legend>
				{{ form|crispy }}
			</fieldset>
			<div class="form-group">
				<button class="btn btn-outline-info" type="submit">Reset Password</button>
			</div>
		</form>
	</div>
{% endblock content %}

users/templates/users/password_reset_done.html
{% extends "blog/base.html"%}
{% load crispy_forms_tags %}
{% block content %}
	<div class="alert alert-info">
		An email has been sent with instructions to reset your password.
	</div>
{% endblock content %}

users/templates/users/register.html
{% extends "blog/index.html"%}
{% load crispy_forms_tags %}

{% block content %}
<div class="col-md-6 col-sm-12 col-lg-6  pb-sm-4">
	<h1 class="text-uppercase text-center text-md-left main-text">Share your experience...</h1>
	<h4 class="text-center text-md-left text-color">sign up to see what goals people are hoping to achieve and offer your support.</h4>
</div>

<div class="content-section">
	<form method="POST">
		{% csrf_token %}
		<fieldset class="form-group">
			<legend clas="border-bottom mb-4">Join Today</legend>
			{{ form|crispy }}
		</fieldset>
		<div class="form-group">
			<button class="btn btn-outline-info" type="submit">Sign Up</button>
		</div>
	</form>
	<div class="border-top pt-3">
		<small class="text-muted">
			Already have An Account?<a class="ml-2" href="{% url 'post:index-home' %}" class=""ml-2>Sign In</a>
		</small>
	</div>
</div>
{% endblock content %}

users/templates/users/signup_profile.html
{% extends "blog/index.html"%}
{% load crispy_forms_tags %}

{% block content %}
<div class="col-md-6 col-sm-12 col-lg-6  pb-sm-4">
	<h1 class="text-uppercase text-center text-md-left main-text">Almost there...</h1>
	<h4 class="text-center text-md-left text-color">don't forget to update your friends on how close you are to achiveing your set goal.</h4>
</div>

<div class="col-md-6 col-sm-12 col-lg-5">
	<div class="content-section">
		<form method="POST">
			{% csrf_token %}
			<fieldset class="form-group">
				<legend clas="border-bottom mb-4">Create Your Profile</legend>
				{{ form|crispy }}
			</fieldset>
			<div class="form-group">
				<button class="btn btn-outline-info" type="submit">Create Profile</button>
			</div>
		</form>
	</div>
</div>
{% endblock content %}

users/templates/users/user_profile_tab.html
<div class="text-center col-md-8 col-lg-7 ">
			<div class="card card-img-top" style="width: 15rem;">
				<img src="{{ user_profile.profile.image.url }}" class="card-img-top" alt="...">
			</div>
			<div class="card-body">
			    <h5 class="card-title">@{{ user_profile.username}}</h5>
			    <h6 class="card-text text-muted">{{ user_profile.profile.first_name | title}} {{ user_profile.profile.last_name | title }}</h6>
			    <p class="card-text">{{ user_profile.profile.bio }}</p>
			    <p class="card-text">{{ user_profile.profile.location | upper}}</p>
			    {% block followbutton %} {% endblock followbutton %}
			</div>
			<div id="top_nav">
			<ul class="nav justify-content-center profile-tabs">
				<li class="nav-item">
				    <h6><a class="nav-link active" href="{% url 'post:user-posts' user_profile.username %}"> ({{ posts_count }}) <BR> <span class="text-muted">Posts</span></a></h6>
				</li>
				<li class="nav-item">
					<h6><a class="nav-link ml-lg-4" href="{% url 'activity:activity-list' user_profile.username %}">({{ activities_count }}) <BR> <span class="text-muted">Activity </span></a></h6>
				</li>
				<li class="nav-item">
					<h6><a class="nav-link ml-lg-4" href="{% url 'relationship:following-list' user_profile.username %}"> ({{ following_count }}) <BR> <span class="text-muted"> Following </span></a></h6>
				</li>
				<li class="nav-item">
					<h6><a class="nav-link ml-lg-4" href="{% url 'relationship:followers-list' user_profile.username %}" tabindex="-1" aria-disabled="true"> ({{ followers_count }}) <BR> <span class="text-muted"> Followers </span> </a></h6>
				</li>
			</ul>
			 </div>
			{% if user == user_profile %}
				<ul class="nav justify-content-center">
					<li class="nav-item">
						<a class="nav-link" href="{% url 'post:favorites_list' user_profile.username %}">Favorite</a>
					</li>
					<li class="nav-item">
						<a class="nav-link" href="{% url 'activity:bookmark-list' %}">Bookmarks</a>
					</li>
				</ul>
			{% endif %}
		</div>